apiVersion: v1
kind: Secret
metadata:
  name: nifty-secrets
type: Opaque
stringData:
  # Base64 encoding is not required when using stringData
  DB_PASSWORD: postgres
  SECRET_KEY: "change-me-in-production"
