# Generated by Django 6.0.5 on 2026-05-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'dim_company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HealthLabel',
            fields=[
                ('health_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'dim_health_label',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sectors',
                'db_table': 'dim_sector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('period_name', models.CharField(max_length=20)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_year',
                'managed': True,
                'unique_together': {('fiscal_year', 'period_name')},
            },
        ),
        migrations.CreateModel(
            name='ProsCons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PROS', 'PROS'), ('CONS', 'CONS')], max_length=10)),
                ('point', models.TextField()),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.company')),
            ],
            options={
                'db_table': 'fact_pros_cons',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, db_column='sector_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.sector'),
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operating_cash_flow', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('investing_cash_flow', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('financing_cash_flow', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('free_cash_flow', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.company')),
                ('year', models.ForeignKey(blank=True, db_column='year_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear')),
            ],
            options={
                'db_table': 'fact_cash_flow',
                'managed': True,
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equity_capital', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('reserves', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('borrowings', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('other_liabilities', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('fixed_assets', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('cwip', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('other_assets', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('debt_to_equity', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.company')),
                ('year', models.ForeignKey(blank=True, db_column='year_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear')),
            ],
            options={
                'db_table': 'fact_balance_sheet',
                'managed': True,
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('stock_pe', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('roce_pct', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('roe_pct', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('interest_coverage', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.company')),
                ('year', models.ForeignKey(blank=True, db_column='year_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear')),
            ],
            options={
                'db_table': 'fact_analysis',
                'managed': True,
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MLScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('probability_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.company')),
                ('health', models.ForeignKey(blank=True, db_column='health_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.healthlabel')),
                ('year', models.ForeignKey(blank=True, db_column='year_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear')),
            ],
            options={
                'db_table': 'fact_ml_scores',
                'managed': True,
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('dividend_payout_pct', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('net_profit_margin_pct', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('expense_ratio_pct', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.company')),
                ('year', models.ForeignKey(blank=True, db_column='year_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear')),
            ],
            options={
                'db_table': 'fact_profit_loss',
                'managed': True,
                'unique_together': {('company', 'year')},
            },
        ),
    ]
