# Generated by Django 6.0.5 on 2026-05-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='balancesheet',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cashflow',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='healthlabel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mlscore',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profitloss',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proscons',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'managed': True, 'verbose_name_plural': 'Sectors'},
        ),
    ]
