# Generated by Django 6.0.5 on 2026-05-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analysis_options_alter_balancesheet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='company',
            field=models.ForeignKey(db_column='company_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='year',
            field=models.ForeignKey(db_column='year_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='company',
            field=models.ForeignKey(db_column='company_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='year',
            field=models.ForeignKey(db_column='year_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow',
            name='company',
            field=models.ForeignKey(db_column='company_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow',
            name='year',
            field=models.ForeignKey(db_column='year_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, db_column='sector_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.sector'),
        ),
        migrations.AddField(
            model_name='mlscore',
            name='company',
            field=models.ForeignKey(db_column='company_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlscore',
            name='health',
            field=models.ForeignKey(db_column='health_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.healthlabel'),
        ),
        migrations.AddField(
            model_name='mlscore',
            name='year',
            field=models.ForeignKey(db_column='year_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitloss',
            name='company',
            field=models.ForeignKey(db_column='company_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profitloss',
            name='year',
            field=models.ForeignKey(db_column='year_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.fiscalyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proscons',
            name='company',
            field=models.ForeignKey(db_column='company_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together={('company', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together={('company', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together={('company', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('fiscal_year', 'period_name')},
        ),
        migrations.AlterUniqueTogether(
            name='mlscore',
            unique_together={('company', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='profitloss',
            unique_together={('company', 'year')},
        ),
    ]
